Experiment 16

1. Write a NumPy program to reverse an array (first element becomes last).

In [ ]:
import numpy as npy
arr1=npy.array([1, 2, 3, 6, 4, 5])
r_arr1=npy.flip(arr1)
print("Original Array:",arr1)
print("Reversed Array:", str(r_arr1))

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]


2.   Write a NumPy program to create a 2-dimensional array of size 2 x 3 also print the shape, type and data type of the array.


In [ ]:
import numpy as npy
arr_1=npy.array([[2, 4, 6], [6, 8, 10]])
print("2D Array:\n",arr_1)
print("Array Shape:",arr_1.shape)
print("Array Type:",type(arr_1))
print("Array Data Type:",arr_1.dtype)

2D Array:
 [[ 2  4  6]
 [ 6  8 10]]
Array Shape: (2, 3)
Array Type: <class 'numpy.ndarray'>
Array Data Type: int64


3.   Write a NumPy program to create a 2-D array with ones on the diagonal and zeros elsewhere.


In [ ]:
import numpy as npy
arr_1=npy.diagflat([1,1,1,1,1])
print("Array with ones on the diagonal and zeros elsewhere:\n",arr_1)

Array with ones on the diagonal and zeros elsewhere:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


4.   Write a NumPy program to multiply and add two 3 x 3 matrices.


In [ ]:
import numpy as npy
mat1=([1,3,9],[1,4,2],[5,2,9])
mat2=([3,4,7],[5,7,2],[4,1,7])
mat_m=npy.dot(mat1,mat2)
mat_a=npy.add(mat1,mat2)
print("Matrix 1:")
for i in range (3):
  print(mat1[i])
print("\nMatrix 2:")
for i in range (3):
  print(mat2[i])
print("\nMultiplication:\n",mat_m)
print("\nAddition:\n",mat_a)

Matrix 1:
[1, 3, 9]
[1, 4, 2]
[5, 2, 9]

Matrix 2:
[3, 4, 7]
[5, 7, 2]
[4, 1, 7]

Multiplication:
 [[ 54  34  76]
 [ 31  34  29]
 [ 61  43 102]]

Addition:
 [[ 4  7 16]
 [ 6 11  4]
 [ 9  3 16]]


5.   Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degrees.


In [ ]:
import numpy as npy
arr1=npy.array((0.,30.,45.,60.,90.,180.))
print("Array of angles given in degrees:\n", arr1)
print("\nTrignometric Sine:\n",npy.sin(arr1))
print("\nTrignometric Cosine:\n",npy.cos(arr1))
print("\nTrignometric Tangent:\n",npy.tan(arr1))

Array of angles given in degrees:
 [  0.  30.  45.  60.  90. 180.]

Trignometric Sine:
 [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666 -0.80115264]

Trignometric Cosine:
 [ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362 -0.59846007]

Trignometric Tangent:
 [ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041  1.33869021]


6.   Write a NumPy program to compute exponential, element-wise of a given array.

In [ ]:
import numpy as npy
arr1=npy.array([1, 3, 5, 7])
print("Original array: ",arr1)
exp_arr1=npy.exp(arr1)
print("\nExponential, element-wise: ",exp_arr1)

Original array:  [1 3 5 7]

Exponential, element-wise:  [   2.71828183   20.08553692  148.4131591  1096.63315843]
